#!/usr/bin/env bash
# This script displays "Best School" 10 times with an iteration
b=10
while [ "$b" -gt 0 ]
do
    echo "Best School"
    if [ "$b" -eq 2 ]
    then
        echo "Hi"
    fi
    b=$((b - 1))
done
i=$b
